name: publish

on:
  push:
    branches:
      - master

jobs:
  publish-image:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build the CICD Docker image
      run: |
        docker build . --tag ghcr.io/ysoftdevs/git-yq:latest
        docker run ghcr.io/ysoftdevs/git-yq:latest
        docker push ghcr.io/ysoftdevs/git-yq:latest
